### ISSUE TITLE
Questions about torch_norm_factor code

### ISSUE THREAD

**Issue by akashsengupta1997** [Davmo049/Public_prob_orientation_estimation_with_matrix_fisher_distributions#1]
Hi, thanks for your very interesting work!

I have some questions about the computation of the log normalisation constant in torch_norm_factor.py.

1) In integrand_cdiff, shouldn't line 61 be i3 = (x-1) instead of i3 = x, for this to be consistent with equation (87) in https://arxiv.org/pdf/1710.03746.pdf ? It seems like there is a factor of (u-1) in the integrand and not just u?

2) In class_logC_F.forward, what is the purpose of log_supress on line 75? It seems to be the sum of the input singular values = trace(S) but I'm not sure why this needs to be added to log_factor which already computes the log normalising constant (after exponential suppression)?

Thanks!

**Comment by akashsengupta1997** [comment]
Actually I may have figured out 2) - is it due to the additional tr(S) term in the matrix Fisher pdf written in terms of the exponentially-suppressed normalisation constant (equation (82) in the paper above)?

Am still unclear about 1) though.

**Comment by akashsengupta1997** [comment]
Nevermind, 1) follows from writing out the gradient fully...

**Comment by Davmo049** [comment]
Hey I just saw your mail

1) for line 61 i3=x.view(1, -1). This operation doesn't do anything arithmetically. It is just a tensor dimension change. x has dimension R^N and i3 has dimension R^{1xN} with the same elements.

2) Just like you said we compute log(exp(a(v))) = log(exp(v+\hat{a}(v)) = log(exp(v))*exp(\hat{a}(v)) = log(exp(v)))+log(exp(\hat{a}(v)) = v + log(exp(\hat{a}(v))
so the "free" v is a remainder of using hat{a} instead of a.
we use \hat{a} instead of a due to numerical (accuracy) reasons.

It is nice that you have read my paper and are going through my code. What are you working on?

For future correspondance please use the email adress in the paper. I do not check github messages regularly, I mainly use github for its git functionality/backup/reproducability.)
