### ISSUE TITLE
Missing trace?

### ISSUE THREAD

**Issue by airalcorn2** [Davmo049/Public_prob_orientation_estimation_with_matrix_fisher_distributions#2]
Hi. Thank you for releasing your code. Based on Equation (5) from the paper, should there be a trace operation in the `KL_Fisher` loss function [here](https://github.com/Davmo049/Public_prob_orientation_estimation_with_matrix_fisher_distributions/blob/2f78fbcfe6b04d5f1cdb997025d1df9446413cb4/loss.py#L209)?

https://github.com/Davmo049/Public_prob_orientation_estimation_with_matrix_fisher_distributions/blob/2f78fbcfe6b04d5f1cdb997025d1df9446413cb4/loss.py#L209

**Comment by Davmo049** [comment]
The implementation is correct as is. Therefore I will close this issue.
Trace is missing due to optimization of code.
tr(A^TR) = <A, R>_F
where <A,R>_F. One implementation of this is to simply do a normal dot product of a flattened A and R
(see https://en.wikipedia.org/wiki/Frobenius_inner_product for reference, the complex conjugate disappears since all values are real.)
Doing things this way requires slightly less compute and memory, not that it matters since the heavy part is the CNN anyway.

Thank you for prrofreading the code.

Best
  David

**Comment by Davmo049** [comment]
I'm pretty sure its correct. trace of matrix multiplication turns into a
dot product for flattened matrices that way you do not need to compute off
diagonal elements.

consider trace([[a1, a2, a3], [a4,a5,a6], [a7,a8, a9]]^T, [[b1, b2, b3],
[b4, b5, b6], [b7,b8,b9]]) = trace([[a1b1+a2b2+a2b3, -, -], [-,
a4b4+a5b5+a6b6, -], [-, -, a7b7+a8b8+a9b9]] = a^T b

But it is good that you read the source to understand and to find bugs.

Best
  David

**Comment by airalcorn2** [comment]
Thanks for your prompt reply. That's probably an equivalence I should be familiar with, but I'd either forgotten it or not come across it yet!
